person_detector:
  name: opencv_yolo
  checkpoint_path: ./data/yolov4_tiny

image_transformation: homography

calibration:
  pkl_file_path: ./data/calibration.pkl

social_distancing:
  distance_threshold_ft: 4